version: "3.3"

services:
  # production containers
  scraper:
    build: ./scraper
    container_name: scraper
    volumes:
      - scraper-data:/data/scraped/

  mongo:
    image: mongo:4.4.1
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: upa
      MONGO_INITDB_ROOT_PASSWORD: upa
    volumes:
      - mongo-data:/data/db

  # TODO: container for data computation

  postgres:
    image: postgres:12.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: upa
      POSTGRES_PASSWORD: upa
      POSTGRES_DB: upa
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # TODO: presentation app container

  # admin containers
  mongo-admin:
    image: mongo-express
    container_name: mongo-admin
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: upa
      ME_CONFIG_MONGODB_ADMINPASSWORD: upa

  postgres-admin:
    container_name: postgres-admin
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8082:8080

volumes:
  mongo-data:
  postgres-data:
  scraper-data: