# Generated by Django 3.1.3 on 2020-11-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('wmo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=128)),
                ('station_name', models.CharField(max_length=128)),
                ('station_height', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'db_table': 'station',
            },
        ),
    ]
