# Generated by Django 3.1.3 on 2020-11-19 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TemperatureRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('average_temperature', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.station')),
            ],
            options={
                'verbose_name': 'Temperature Rank',
                'verbose_name_plural': 'Temperature Ranks',
                'db_table': 'temperature_rank',
            },
        ),
        migrations.CreateModel(
            name='RainfallRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('rainfall', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.station')),
            ],
            options={
                'verbose_name': 'Rainfall Rank',
                'verbose_name_plural': 'Rainfall Ranks',
                'db_table': 'rainfall_rank',
            },
        ),
    ]
