# Generated by Django 3.1.3 on 2020-11-19 13:18

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20201119_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('rainfall_from_morning', models.FloatField()),
                ('rainfall_last_day', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.station')),
            ],
            options={
                'verbose_name': 'Rainfall',
                'verbose_name_plural': 'Rainfalls',
                'db_table': 'rainfall',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.station')),
            ],
            options={
                'verbose_name': 'Temperature',
                'verbose_name_plural': 'Temperatures',
                'db_table': 'temperature',
            },
        ),
        migrations.RemoveField(
            model_name='temperaturerank',
            name='station',
        ),
        migrations.DeleteModel(
            name='RainfallRank',
        ),
        migrations.DeleteModel(
            name='TemperatureRank',
        ),
    ]
