# Generated by Django 3.1.3 on 2020-11-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20201119_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rainfall',
            options={'ordering': ('timestamp', 'station'), 'verbose_name': 'Rainfall', 'verbose_name_plural': 'Rainfalls'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ('timestamp', 'station'), 'verbose_name': 'Temperature', 'verbose_name_plural': 'Temperatures'},
        ),
        migrations.AlterUniqueTogether(
            name='rainfall',
            unique_together={('station', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='temperature',
            unique_together={('station', 'timestamp')},
        ),
    ]
