# Generated by Django 3.1.3 on 2020-11-21 16:32

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0005_auto_20201120_1021'),
    ]

    operations = [
        RunSQL("""
        CREATE OR REPLACE VIEW v_rainfall AS
SELECT r.timestamp,
       r.rainfall_from_morning,
       r.rainfall_last_day,
       r.station_id,
       s.station_name,
       s.station_height,
       s.location,
       s.latitude,
       s.longitude
FROM rainfall r
         INNER JOIN station s on s.wmo_id = r.station_id;
        """, """
DROP VIEW v_rainfall;
        """)
    ]
